from .animal import Animal
from .alligator import Alligator
from .burro import Burro
from .chameleon import Chameleon
from .copperhead import Copperhead
from .cow import Cow
from .donkey import Donkey
from .frog import Frog
from .gilaMonster import GilaMonster
from .goat import Goat
from .goldfish import Goldfish
from .koi import Koi
from .llama import Llama
from .mallard import Mallard
from .pig import Pig
from .ratsnake import Ratsnake
from .turtle import Turtle